export const USER_NOTES_REQUEST = 'USER_NOTES_REQUEST'
export const USER_NOTES_SUCCESS = 'USER_NOTES_SUCCESS'
export const USER_NOTES_FAIL = 'USER_NOTES_FAIL'

export const USER_NOTE_DETAIL_REQUEST = 'USER_NOTE_DETAIL_REQUEST'
export const USER_NOTE_DETAIL_SUCCESS = 'USER_NOTE_DETAIL_SUCCESS'
export const USER_NOTE_DETAIL_FAIL = 'USER_NOTE_DETAIL_FAIL'

export const USER_NOTE_DETAIL_UPDATE_REQUEST = 'USER_NOTE_DETAIL_UPDATE_REQUEST'
export const USER_NOTE_DETAIL_UPDATE_SUCCESS = 'USER_NOTE_DETAIL_UPDATE_SUCCESS'
export const USER_NOTE_DETAIL_UPDATE_FAIL = 'USER_NOTE_DETAIL_UPDATE_FAIL'