export const COLLABORATION_REQUEST = 'COLLABORATION_REQUEST'
export const COLLABORATION_SUCCESS = 'COLLABORATION_SUCCESS'
export const COLLABORATION_FAIL = 'COLLABORATION_FAIL'
export const COLLABORATION_RESET = 'COLLABORATION_RESET'